# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'display_location_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(10, 10, 600, 300))
        self.graphicsView.setMouseTracking(True)
        self.graphicsView.setInputMethodHints(QtCore.Qt.ImhNone)
        self.graphicsView.setSceneRect(QtCore.QRectF(0.0, 0.0, 0.0, 0.0))
        self.graphicsView.setObjectName("graphicsView")
        self.labelLatLon = QtWidgets.QLabel(self.centralwidget)
        self.labelLatLon.setGeometry(QtCore.QRect(10, 320, 501, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelLatLon.setFont(font)
        self.labelLatLon.setObjectName("labelLatLon")
        self.textEditLatLon = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditLatLon.setGeometry(QtCore.QRect(10, 340, 501, 64))
        self.textEditLatLon.setObjectName("textEditLatLon")
        self.pushButtonNewRoute = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonNewRoute.setGeometry(QtCore.QRect(530, 330, 81, 31))
        self.pushButtonNewRoute.setObjectName("pushButtonNewRoute")
        self.pushButtonRandomRoute = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonRandomRoute.setGeometry(QtCore.QRect(530, 370, 81, 31))
        self.pushButtonRandomRoute.setObjectName("pushButtonRandomRoute")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 18))
        self.menubar.setObjectName("menubar")
        self.menuExport = QtWidgets.QMenu(self.menubar)
        self.menuExport.setObjectName("menuExport")
        self.menuImport = QtWidgets.QMenu(self.menubar)
        self.menuImport.setObjectName("menuImport")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExportCSV = QtWidgets.QAction(MainWindow)
        self.actionExportCSV.setObjectName("actionExportCSV")
        self.actionExportPyomo = QtWidgets.QAction(MainWindow)
        self.actionExportPyomo.setObjectName("actionExportPyomo")
        self.actionImportCSV = QtWidgets.QAction(MainWindow)
        self.actionImportCSV.setObjectName("actionImportCSV")
        self.actionImportPyomo = QtWidgets.QAction(MainWindow)
        self.actionImportPyomo.setObjectName("actionImportPyomo")
        self.menuExport.addAction(self.actionExportCSV)
        self.menuExport.addAction(self.actionExportPyomo)
        self.menuImport.addAction(self.actionImportCSV)
        self.menuImport.addAction(self.actionImportPyomo)
        self.menubar.addAction(self.menuExport.menuAction())
        self.menubar.addAction(self.menuImport.menuAction())

        self.retranslateUi(MainWindow)
        self.actionExportCSV.triggered.connect(MainWindow.update)
        self.textEditLatLon.textChanged.connect(MainWindow.update)
        self.actionImportCSV.triggered.connect(MainWindow.update)
        self.pushButtonNewRoute.pressed.connect(MainWindow.update)
        self.pushButtonRandomRoute.pressed.connect(MainWindow.update)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelLatLon.setText(_translate("MainWindow", "Sequence of Lat,Lon coordinates"))
        self.textEditLatLon.setPlaceholderText(_translate("MainWindow", "Enter Lat#,Lon#;...\\n...repeat"))
        self.pushButtonNewRoute.setText(_translate("MainWindow", "New Route"))
        self.pushButtonRandomRoute.setText(_translate("MainWindow", "Random Route"))
        self.menuExport.setTitle(_translate("MainWindow", "Export"))
        self.menuImport.setTitle(_translate("MainWindow", "Import"))
        self.actionExportCSV.setText(_translate("MainWindow", "CSV file"))
        self.actionExportPyomo.setText(_translate("MainWindow", "Pyomo file"))
        self.actionImportCSV.setText(_translate("MainWindow", "CSV file"))
        self.actionImportPyomo.setText(_translate("MainWindow", "Pyomo file"))
