# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'display_location.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(10, 10, 300, 300))
        self.graphicsView.setObjectName("graphicsView")
        self.labelEndLatLon = QtWidgets.QLabel(self.centralwidget)
        self.labelEndLatLon.setGeometry(QtCore.QRect(320, 110, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelEndLatLon.setFont(font)
        self.labelEndLatLon.setObjectName("labelEndLatLon")
        self.labelStartLatLon = QtWidgets.QLabel(self.centralwidget)
        self.labelStartLatLon.setGeometry(QtCore.QRect(320, 10, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelStartLatLon.setFont(font)
        self.labelStartLatLon.setObjectName("labelStartLatLon")
        self.textEditStartLatLon = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditStartLatLon.setGeometry(QtCore.QRect(320, 30, 131, 64))
        self.textEditStartLatLon.setObjectName("textEditStartLatLon")
        self.textEditEndLatLon = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditEndLatLon.setGeometry(QtCore.QRect(320, 130, 131, 64))
        self.textEditEndLatLon.setObjectName("textEditEndLatLon")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 18))
        self.menubar.setObjectName("menubar")
        self.menuExport = QtWidgets.QMenu(self.menubar)
        self.menuExport.setObjectName("menuExport")
        self.menuImport = QtWidgets.QMenu(self.menubar)
        self.menuImport.setObjectName("menuImport")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExportCSV = QtWidgets.QAction(MainWindow)
        self.actionExportCSV.setObjectName("actionExportCSV")
        self.actionExportPyomo = QtWidgets.QAction(MainWindow)
        self.actionExportPyomo.setObjectName("actionExportPyomo")
        self.actionImportCSV = QtWidgets.QAction(MainWindow)
        self.actionImportCSV.setObjectName("actionImportCSV")
        self.actionImportPyomo = QtWidgets.QAction(MainWindow)
        self.actionImportPyomo.setObjectName("actionImportPyomo")
        self.menuExport.addAction(self.actionExportCSV)
        self.menuExport.addAction(self.actionExportPyomo)
        self.menuImport.addAction(self.actionImportCSV)
        self.menuImport.addAction(self.actionImportPyomo)
        self.menubar.addAction(self.menuExport.menuAction())
        self.menubar.addAction(self.menuImport.menuAction())

        self.retranslateUi(MainWindow)
        self.actionExportCSV.triggered.connect(MainWindow.update)
        self.textEditStartLatLon.textChanged.connect(MainWindow.update)
        self.textEditEndLatLon.textChanged.connect(MainWindow.update)
        self.actionImportCSV.triggered.connect(MainWindow.update)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelEndLatLon.setText(_translate("MainWindow", "End Lat,Lon coordinates"))
        self.labelStartLatLon.setText(_translate("MainWindow", "Start Lat,Lon coordinates"))
        self.textEditStartLatLon.setPlaceholderText(_translate("MainWindow", "Enter Lat#,Lon#\\n...repeat"))
        self.textEditEndLatLon.setPlaceholderText(_translate("MainWindow", "Enter Lat#,Lon#\\n...repeat"))
        self.menuExport.setTitle(_translate("MainWindow", "Export"))
        self.menuImport.setTitle(_translate("MainWindow", "Import"))
        self.actionExportCSV.setText(_translate("MainWindow", "CSV file"))
        self.actionExportPyomo.setText(_translate("MainWindow", "Pyomo file"))
        self.actionImportCSV.setText(_translate("MainWindow", "CSV file"))
        self.actionImportPyomo.setText(_translate("MainWindow", "Pyomo file"))
